name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        ruby: [ '3.0', '3.1' ]

    env:
      AUTO_CONFIRM_BUILD: true

    steps:
      - uses: actions/checkout@master

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.7'

      - name: Run tests
        run: |
          go version
          bundle exec rspec spec
