name: Publish

# To release a new version of native gems, create a tag and Github release.

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  native:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    name: publish
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      - name: Build gem
        run: |
          bundle exec rake build

      - name: Push gem
        run: |
          gem push pkg/*.gem
